//! Bridge renderers for `histos.json` (PLAN Phase 9).
//!
//! `histos.json` is the single source of truth (`HistoSet::to_json`). These
//! renderers turn the same in-memory accumulator into the formats a
//! collaborator actually opens — without our toolchain growing a ROOT or
//! plotting dependency:
//!
//! - [`make_histos_c`] — a self-contained ROOT macro (`root -l -b -q
//!   make_histos.C`) that builds one `TH1D` per histogram with `Sumw2`,
//!   full bin contents/errors (including under/overflow bins 0 and N+1),
//!   `SetEntries`, and the four stats moments via `PutStats`.
//! - [`to_root_py`] — an uproot 5 + `numpy` script (`python3 to_root.py`)
//!   writing the byte-equivalent `TH1D`s through `uproot.writing.identify`.
//! - [`csv_files`] — one CSV per histogram (`bin_lo,bin_hi,content,error`).
//! - [`svg_files`] — one hand-rolled step-plot SVG per histogram (no
//!   plotting dependency).
//!
//! ROOT bin/stats conventions (SPEC_ROOT_WRITER §2, §4):
//! - `SetBinContent(0, underflow)`, `SetBinContent(i, sumw[i-1])` for
//!   i ∈ 1..=N, `SetBinContent(N+1, overflow)`; `SetBinError(i,
//!   sqrt(sumw2))` over the same index range.
//! - `SetEntries(entries)` is the raw fill count (ROOT `fEntries`).
//! - `PutStats({tsumw, tsumw2, tsumwx, tsumwx2})` writes the in-range
//!   fill-time moments so `GetMean`/`GetStdDev` and merged `hadd` stats stay
//!   exact (ROOT `GetStats` excludes flow bins).
//!
//! The ROOT object name is the **flat, region-prefixed** v1 name
//! (`<region path '/'→'_'>_<histo name>`, ratified 2026-06-12); TDirectories
//! are deferred to v2. Names are stable across runs so `hadd` merges by name.
//!
//! Every renderer is a pure function of the [`HistoSet`] and is
//! byte-deterministic; nothing here reads the clock or the environment.

use adl_interp::{Hist1D, HistoSet};
use std::fmt::Write as _;

/// The flat, region-prefixed ROOT object name (`SR_hmet`). The region path
/// separator `/` (none in v1, but future-proof) collapses to `_`.
///
/// Shared by every bridge renderer AND the native `rootfile` writer so all
/// four outputs (`out.root`, `make_histos.C`, `to_root.py`, CSV/SVG stems)
/// agree on object names and stay `hadd`-mergeable.
pub(crate) fn root_name(region: &str, name: &str) -> String {
    format!("{}_{name}", region.replace('/', "_"))
}

/// A safe filename stem for the per-histogram CSV/SVG files: the flat ROOT
/// name with any character outside `[A-Za-z0-9._-]` replaced by `_`.
fn file_stem(region: &str, name: &str) -> String {
    root_name(region, name)
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || matches!(c, '.' | '_' | '-') {
                c
            } else {
                '_'
            }
        })
        .collect()
}

/// A finite `f64` rendered as shortest round-trip text (serde_json/ryu),
/// shared by every numeric emitter so the bridges agree bit-for-bit with
/// `histos.json`.
fn num(v: f64) -> String {
    serde_json::to_string(&v).expect("finite f64 serializes")
}

/// Per-bin error: ROOT's `sqrt(sumw2)` (we always fill weighted, so the
/// error is the square root of the sum of squared weights).
fn bin_error(sumw2: f64) -> f64 {
    sumw2.sqrt()
}

// --- make_histos.C (ROOT macro) ------------------------------------------

/// Escape a string for a C/C++ double-quoted literal in the ROOT macro.
/// Titles are collaborator-authored ADL text, so backslashes, quotes, and
/// control characters all get escaped rather than trusted.
fn c_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => {
                let _ = write!(out, "\\x{:02x}", c as u32);
            }
            c => out.push(c),
        }
    }
    out
}

/// Render `make_histos.C`: a self-contained ROOT macro writing one `TH1D`
/// per histogram into a `.root` file named after the macro's directory.
#[must_use]
pub fn make_histos_c(set: &HistoSet) -> String {
    let mut s = String::new();
    s.push_str(
        "// Generated by smash2 from histos.json — do not edit.\n\
         // Run:  root -l -b -q make_histos.C\n\
         // Produces histos.root with one TH1D per histogram (flat,\n\
         // region-prefixed names; Sumw2 errors and fill-time stats intact).\n\
         #include \"TFile.h\"\n\
         #include \"TH1D.h\"\n\n\
         void make_histos() {\n\
         \x20 TFile* f = TFile::Open(\"histos.root\", \"RECREATE\");\n\n",
    );

    for fill in &set.histos {
        let h = &fill.hist;
        let rname = root_name(&fill.region, &fill.name);
        let _ = writeln!(s, "  // {} / {}", fill.region, fill.name);
        let _ = writeln!(
            s,
            "  {{\n    TH1D* h = new TH1D(\"{}\", \"{}\", {}, {}, {});",
            c_escape(&rname),
            c_escape(&fill.title),
            h.nbins,
            num(h.lo),
            num(h.hi),
        );
        s.push_str("    h->Sumw2();\n");
        // Underflow (bin 0), in-range bins 1..=N, overflow (bin N+1).
        emit_c_bin(&mut s, 0, h.underflow_w, h.underflow_w2);
        for i in 0..h.nbins as usize {
            #[allow(clippy::cast_possible_truncation)]
            emit_c_bin(&mut s, (i + 1) as i64, h.sumw[i], h.sumw2[i]);
        }
        emit_c_bin(&mut s, i64::from(h.nbins) + 1, h.overflow_w, h.overflow_w2);
        let _ = writeln!(s, "    h->SetEntries({});", h.entries);
        let _ = writeln!(
            s,
            "    Double_t stats[4] = {{{}, {}, {}, {}}};",
            num(h.tsumw),
            num(h.tsumw2),
            num(h.tsumwx),
            num(h.tsumwx2),
        );
        s.push_str("    h->PutStats(stats);\n    h->Write();\n  }\n\n");
    }

    s.push_str("  f->Write();\n  f->Close();\n}\n");
    s
}

fn emit_c_bin(s: &mut String, bin: i64, w: f64, w2: f64) {
    let _ = writeln!(s, "    h->SetBinContent({bin}, {});", num(w));
    let _ = writeln!(s, "    h->SetBinError({bin}, {});", num(bin_error(w2)));
}

// --- to_root.py (uproot 5) -----------------------------------------------

/// Escape a string for a Python single-quoted literal.
fn py_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '\'' => out.push_str("\\'"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => {
                let _ = write!(out, "\\x{:02x}", c as u32);
            }
            c => out.push(c),
        }
    }
    out
}

/// A Python list literal of finite floats, shortest round-trip text.
fn py_float_list(vs: &[f64]) -> String {
    let mut out = String::from("[");
    for (i, &v) in vs.iter().enumerate() {
        if i > 0 {
            out.push_str(", ");
        }
        out.push_str(&num(v));
    }
    out.push(']');
    out
}

/// Render `to_root.py`: an uproot 5 + numpy script writing the
/// byte-equivalent `TH1D`s. Builds each histogram through
/// `uproot.writing.identify.to_TH1x` so `fEntries` and the four stats
/// moments are set exactly (the high-level `hist` path does not preserve
/// raw entry counts or fill-time moments).
#[must_use]
pub fn to_root_py(set: &HistoSet) -> String {
    let mut s = String::new();
    s.push_str(
        "#!/usr/bin/env python3\n\
         \"\"\"Generated by smash2 from histos.json — do not edit.\n\n\
         Run:  python3 to_root.py   (requires uproot>=5 and numpy)\n\
         Produces histos.root with one TH1D per histogram (flat,\n\
         region-prefixed names) byte-equivalent to make_histos.C.\n\
         \"\"\"\n\
         import numpy as np\n\
         import uproot\n\
         from uproot.writing.identify import to_TH1x\n\n\
         def _th1(name, title, nbins, lo, hi, contents, errors2,\n\
         \x20        entries, tsumw, tsumw2, tsumwx, tsumwx2):\n\
         \x20   # contents/errors2 length is nbins+2 (underflow .. overflow).\n\
         \x20   data = np.array(contents, dtype=\">f8\")\n\
         \x20   fSumw2 = np.array(errors2, dtype=\">f8\")\n\
         \x20   return to_TH1x(\n\
         \x20       fName=name, fTitle=title, data=data, fEntries=entries,\n\
         \x20       fTsumw=tsumw, fTsumw2=tsumw2, fTsumwx=tsumwx, fTsumwx2=tsumwx2,\n\
         \x20       fSumw2=fSumw2, fXaxis=uproot.writing.identify.to_TAxis(\n\
         \x20           fName=\"xaxis\", fTitle=\"\", fNbins=nbins, fXmin=lo, fXmax=hi))\n\n\
         def main():\n\
         \x20   with uproot.recreate(\"histos.root\") as f:\n",
    );

    for fill in &set.histos {
        let h = &fill.hist;
        let rname = root_name(&fill.region, &fill.name);
        // contents/errors2 ordered underflow, in-range bins, overflow — the
        // TArrayD layout to_TH1x expects (length nbins+2).
        let contents = flow_contents(h);
        let errors2 = flow_errors2(h);
        let _ = writeln!(s, "        # {} / {}", fill.region, fill.name);
        let _ = writeln!(
            s,
            "        f[{q:?}] = _th1(\n            name='{name}', title='{title}',\n\
             \x20           nbins={nbins}, lo={lo}, hi={hi},\n\
             \x20           contents={contents},\n\
             \x20           errors2={errors2},\n\
             \x20           entries={entries}, tsumw={tsumw}, tsumw2={tsumw2},\n\
             \x20           tsumwx={tsumwx}, tsumwx2={tsumwx2})",
            q = rname,
            name = py_escape(&rname),
            title = py_escape(&fill.title),
            nbins = h.nbins,
            lo = num(h.lo),
            hi = num(h.hi),
            contents = py_float_list(&contents),
            errors2 = py_float_list(&errors2),
            entries = h.entries,
            tsumw = num(h.tsumw),
            tsumw2 = num(h.tsumw2),
            tsumwx = num(h.tsumwx),
            tsumwx2 = num(h.tsumwx2),
        );
    }

    s.push_str("\nif __name__ == \"__main__\":\n    main()\n");
    s
}

/// Bin contents in ROOT TArrayD order: `[underflow, bin1.., overflow]`.
fn flow_contents(h: &Hist1D) -> Vec<f64> {
    let mut v = Vec::with_capacity(h.sumw.len() + 2);
    v.push(h.underflow_w);
    v.extend_from_slice(&h.sumw);
    v.push(h.overflow_w);
    v
}

/// Bin sum-of-weights² (fSumw2 array) in the same flow order.
fn flow_errors2(h: &Hist1D) -> Vec<f64> {
    let mut v = Vec::with_capacity(h.sumw2.len() + 2);
    v.push(h.underflow_w2);
    v.extend_from_slice(&h.sumw2);
    v.push(h.overflow_w2);
    v
}

// --- CSV ------------------------------------------------------------------

/// One CSV per histogram. Each is `(filename, contents)`; the filename is
/// `<flat-name>.csv`. Rows are the in-range bins only (`bin_lo,bin_hi,
/// content,error`); flow bins are out of the visible axis and live in the
/// JSON. Header line included.
#[must_use]
pub fn csv_files(set: &HistoSet) -> Vec<(String, String)> {
    set.histos
        .iter()
        .map(|fill| {
            let h = &fill.hist;
            let width = (h.hi - h.lo) / f64::from(h.nbins);
            let mut body = String::from("bin_lo,bin_hi,content,error\n");
            for i in 0..h.nbins as usize {
                #[allow(clippy::cast_precision_loss)]
                let lo = h.lo + width * i as f64;
                #[allow(clippy::cast_precision_loss)]
                let hi = h.lo + width * (i + 1) as f64;
                let _ = writeln!(
                    body,
                    "{},{},{},{}",
                    num(lo),
                    num(hi),
                    num(h.sumw[i]),
                    num(bin_error(h.sumw2[i])),
                );
            }
            (format!("{}.csv", file_stem(&fill.region, &fill.name)), body)
        })
        .collect()
}

// --- SVG (hand-rolled step plot) -----------------------------------------

/// Escape text for an SVG text/attribute context.
fn svg_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&apos;"),
            c => out.push(c),
        }
    }
    out
}

/// Format a coordinate with at most 3 decimals, trailing zeros trimmed, so
/// the SVG path data stays compact and byte-stable.
fn coord(v: f64) -> String {
    let mut t = format!("{v:.3}");
    if t.contains('.') {
        while t.ends_with('0') {
            t.pop();
        }
        if t.ends_with('.') {
            t.pop();
        }
    }
    if t == "-0" { "0".to_owned() } else { t }
}

/// One quick-look step-plot SVG per histogram. Hand-rolled (no plotting
/// dependency): a fixed 640×400 viewport, in-range bins drawn as a filled
/// step outline with the y-axis scaled to the tallest bin; flow bins are
/// noted in the caption but not drawn (they sit off the visible axis).
#[must_use]
pub fn svg_files(set: &HistoSet) -> Vec<(String, String)> {
    set.histos
        .iter()
        .map(|fill| {
            (
                format!("{}.svg", file_stem(&fill.region, &fill.name)),
                svg_one(fill.title.as_str(), &fill.region, &fill.name, &fill.hist),
            )
        })
        .collect()
}

const SVG_W: f64 = 640.0;
const SVG_H: f64 = 400.0;
const PAD_L: f64 = 56.0;
const PAD_R: f64 = 16.0;
const PAD_T: f64 = 36.0;
const PAD_B: f64 = 44.0;

fn svg_one(title: &str, region: &str, name: &str, h: &Hist1D) -> String {
    let plot_w = SVG_W - PAD_L - PAD_R;
    let plot_h = SVG_H - PAD_T - PAD_B;
    let ymax = h.sumw.iter().copied().fold(0.0_f64, f64::max).max(1.0);

    // x maps [lo, hi] across the plot width; y maps [0, ymax] up from the
    // baseline (SVG y grows downward).
    let x_at = |v: f64| PAD_L + (v - h.lo) / (h.hi - h.lo) * plot_w;
    let y_at = |v: f64| PAD_T + plot_h - (v / ymax) * plot_h;
    let width = (h.hi - h.lo) / f64::from(h.nbins);

    // Step outline: start at the baseline, walk each bin's top edge, return
    // to the baseline — one closed polygon for a clean filled quick-look.
    let mut d = String::new();
    let _ = write!(d, "M {} {}", coord(x_at(h.lo)), coord(y_at(0.0)));
    for i in 0..h.nbins as usize {
        #[allow(clippy::cast_precision_loss)]
        let bl = h.lo + width * i as f64;
        #[allow(clippy::cast_precision_loss)]
        let br = h.lo + width * (i + 1) as f64;
        let top = y_at(h.sumw[i]);
        let _ = write!(d, " L {} {}", coord(x_at(bl)), coord(top));
        let _ = write!(d, " L {} {}", coord(x_at(br)), coord(top));
    }
    let _ = write!(d, " L {} {} Z", coord(x_at(h.hi)), coord(y_at(0.0)));

    let baseline = coord(y_at(0.0));
    let flow_note = if h.underflow_w != 0.0 || h.overflow_w != 0.0 {
        format!(
            "  underflow={}  overflow={}",
            num(h.underflow_w),
            num(h.overflow_w)
        )
    } else {
        String::new()
    };

    let mut s = String::new();
    let _ = write!(
        s,
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\
         <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"{w}\" height=\"{h_}\" \
         viewBox=\"0 0 {w} {h_}\" font-family=\"sans-serif\">\n\
         \x20 <rect width=\"{w}\" height=\"{h_}\" fill=\"white\"/>\n\
         \x20 <text x=\"{tx}\" y=\"20\" font-size=\"15\" text-anchor=\"middle\">{title}</text>\n\
         \x20 <text x=\"{tx}\" y=\"{cap_y}\" font-size=\"11\" text-anchor=\"middle\" \
         fill=\"#555\">{rname}  [{lo}, {hi}) x{nbins}  entries={entries}{flow}</text>\n\
         \x20 <line x1=\"{px}\" y1=\"{base}\" x2=\"{pxr}\" y2=\"{base}\" stroke=\"#000\"/>\n\
         \x20 <line x1=\"{px}\" y1=\"{ptop}\" x2=\"{px}\" y2=\"{base}\" stroke=\"#000\"/>\n\
         \x20 <text x=\"{px}\" y=\"{ymax_y}\" font-size=\"10\" text-anchor=\"end\" \
         fill=\"#333\">{ymax}</text>\n\
         \x20 <path d=\"{d}\" fill=\"#cfe3f7\" stroke=\"#1f6fc4\" stroke-width=\"1\"/>\n\
         </svg>\n",
        w = coord(SVG_W),
        h_ = coord(SVG_H),
        tx = coord(SVG_W / 2.0),
        title = svg_escape(title),
        cap_y = coord(SVG_H - 12.0),
        rname = svg_escape(&root_name(region, name)),
        lo = num(h.lo),
        hi = num(h.hi),
        nbins = h.nbins,
        entries = h.entries,
        flow = svg_escape(&flow_note),
        px = coord(PAD_L),
        pxr = coord(SVG_W - PAD_R),
        base = baseline,
        ptop = coord(PAD_T),
        ymax_y = coord(PAD_T + 4.0),
        ymax = num(ymax),
        d = d,
    );
    s
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn root_name_is_region_prefixed_and_path_safe() {
        assert_eq!(root_name("SR", "hmet"), "SR_hmet");
        assert_eq!(root_name("a/b", "h"), "a_b_h");
    }

    #[test]
    fn c_escape_handles_quotes_backslashes_controls() {
        assert_eq!(c_escape("a\"b\\c"), "a\\\"b\\\\c");
        assert_eq!(c_escape("x\ty"), "x\\ty");
        assert_eq!(c_escape("\u{1}"), "\\x01");
    }

    #[test]
    fn coord_trims_and_kills_negative_zero() {
        assert_eq!(coord(1.0), "1");
        assert_eq!(coord(1.500), "1.5");
        assert_eq!(coord(-0.0), "0");
    }
}
