//! Generator for `to_jsonl.py` — the independent uproot oracle
//! (SPEC_EVENT_PIPELINE §1.1 path (b)).
//!
//! The script reads the same ROOT file with uproot 5.x (a reader that
//! shares no code with oxyroot) and must produce **byte-identical** JSONL
//! to the native reader. It is generated from the same [`Profile`] data
//! table that drives the native path, so the *mapping* has one source of
//! truth while the *readers* stay independent. It doubles as the no-Rust
//! fallback for collaborators.
//!
//! Number text: the native side emits serde_json/ryu shortest-round-trip
//! floats. The script's `jnum` converts CPython `repr` (also shortest
//! round-trip — same digit strings) to the same notation: ryu's plain
//! decimal region is exponent −5..=15 where CPython switches to
//! scientific below −4, and CPython zero-pads negative exponents where
//! ryu does not. Positive exponents (≥ 16) already agree (`1e+16`).

use crate::profile::{LeafKind, Profile};
use std::fmt::Write as _;

/// Canonical JSON text of an f64 (shared with the reader's emitter).
fn jnum(v: f64) -> String {
    serde_json::to_string(&v).expect("finite f64 serializes")
}

fn py_str(s: &str) -> String {
    format!("\"{}\"", s.replace('\\', "\\\\").replace('"', "\\\""))
}

/// Render the `to_jsonl.py` oracle script for `profile`.
#[must_use]
pub fn to_jsonl_py(profile: &Profile) -> String {
    let mut tables = String::new();

    // COLLECTIONS = [(branch, key, [(leaf, prop, kind), ...], [(prop, text), ...]), ...]
    tables.push_str("COLLECTIONS = [\n");
    for c in &profile.collections {
        let leaves: Vec<String> = c
            .leaves
            .iter()
            .map(|l| {
                let kind = match l.kind {
                    LeafKind::F32 => "\"f\"".to_owned(),
                    LeafKind::I32 => "\"i\"".to_owned(),
                    LeafKind::TagBit(bit) => format!("(\"tag\", {bit})"),
                };
                format!("({}, {}, {kind})", py_str(&l.leaf), py_str(&l.prop))
            })
            .collect();
        let constants: Vec<String> = c
            .constants
            .iter()
            .map(|(prop, v)| format!("({}, {})", py_str(prop), py_str(&jnum(*v))))
            .collect();
        let _ = writeln!(
            tables,
            "    ({}, {}, [{}], [{}]),",
            py_str(&c.branch),
            py_str(&c.key),
            leaves.join(", "),
            constants.join(", ")
        );
    }
    tables.push_str("]\n");

    match &profile.met {
        Some(m) => {
            let _ = writeln!(
                tables,
                "MET = ({}, {}, {})",
                py_str(&m.branch),
                py_str(&m.pt_leaf),
                py_str(&m.phi_leaf)
            );
        }
        None => tables.push_str("MET = None\n"),
    }

    tables.push_str("SCALARS = [\n");
    for s in &profile.scalars {
        let _ = writeln!(
            tables,
            "    ({}, {}, {}),",
            py_str(&s.branch),
            py_str(&s.leaf),
            py_str(&s.key)
        );
    }
    tables.push_str("]\n");

    match &profile.weight {
        Some(w) => {
            let _ = writeln!(
                tables,
                "WEIGHT = ({}, {})",
                py_str(&w.branch),
                py_str(&w.leaf)
            );
        }
        None => tables.push_str("WEIGHT = None\n"),
    }

    let header = format!(
        "#!/usr/bin/env python3\n\
         # to_jsonl.py — generated by smash2 (adl-ingest) for profile {id}.\n\
         # Independent ingestion oracle: reads a Delphes-layout ROOT file with\n\
         # uproot 5.x and writes the canonical JSONL event stream. Output must\n\
         # be byte-identical to `smash2 ingest <file> --profile {name} -o ...`.\n\
         #\n\
         # Usage: python3 to_jsonl.py events.root events.jsonl\n\
         # Needs: uproot 5.x (pip install 'uproot>=5,<6'); see the repo's\n\
         # .venv-uproot for the pinned environment.\n",
        id = profile.id(),
        name = profile.name,
    );

    let tree = py_str(&profile.tree);

    format!(
        r#"{header}
import sys

import uproot

TREE = {tree}
{tables}

def jnum(x):
    """serde_json/ryu-compatible shortest round-trip float text."""
    x = float(x)
    if x != x or x in (float("inf"), float("-inf")):
        raise SystemExit(f"non-finite value {{x!r}} (unrepresentable in canonical JSONL)")
    s = repr(x)
    if "e" not in s:
        return s
    m, e = s.split("e")
    ei = int(e)
    if ei >= 16:
        return f"{{m}}e+{{ei}}"  # CPython and ryu agree here
    if ei == -5:
        # ryu's plain-decimal region reaches e-5; CPython went scientific.
        sign = "-" if m.startswith("-") else ""
        digits = m.lstrip("-").replace(".", "")
        return sign + "0.0000" + digits
    return f"{{m}}e-{{abs(ei)}}"  # strip CPython's zero-padded exponent


def fmt_prop(kind, v):
    if kind == "f":
        return jnum(v)
    if kind == "i":
        return str(int(v))
    tag, bit = kind
    assert tag == "tag"
    return str((int(v) >> bit) & 1)


def main():
    if len(sys.argv) != 3:
        raise SystemExit("usage: to_jsonl.py events.root events.jsonl")
    tree = uproot.open(sys.argv[1])[TREE]
    keys = set(tree.keys())

    def has(branch, leaf):
        return f"{{branch}}/{{branch}}.{{leaf}}" in keys or f"{{branch}}.{{leaf}}" in keys

    def arr(branch, leaf):
        name = f"{{branch}}/{{branch}}.{{leaf}}"
        if name not in keys:
            name = f"{{branch}}.{{leaf}}"
        return tree[name].array()

    def counter(branch):
        return tree[f"{{branch}}_size"].array()

    n = tree.num_entries
    cols = []
    for branch, key, leaves, constants in COLLECTIONS:
        if not any(has(branch, leaf) for leaf, _, _ in leaves) and f"{{branch}}_size" not in keys:
            continue  # collection absent from this file
        counts = counter(branch)
        data = [(prop, kind, arr(branch, leaf)) for leaf, prop, kind in leaves]
        for prop, _, a in data:
            for e in range(n):
                if len(a[e]) != counts[e]:
                    raise SystemExit(
                        f"{{branch}}.{{prop}}: entry {{e}}: {{len(a[e])}} values vs counter {{counts[e]}}"
                    )
        cols.append((key, counts, data, constants))

    met = None
    if MET is not None and (has(MET[0], MET[1]) or has(MET[0], MET[2])):
        met = (counter(MET[0]), arr(MET[0], MET[1]), arr(MET[0], MET[2]))
    scalars = [
        (key, counter(branch), arr(branch, leaf))
        for branch, leaf, key in SCALARS
        if has(branch, leaf)
    ]
    weight = None
    if WEIGHT is not None and has(WEIGHT[0], WEIGHT[1]):
        weight = (counter(WEIGHT[0]), arr(WEIGHT[0], WEIGHT[1]))

    with open(sys.argv[2], "w", encoding="utf-8", newline="\n") as out:
        for e in range(n):
            parts = []
            for key, counts, data, constants in cols:
                objs = []
                prev_pt = None
                for i in range(int(counts[e])):
                    props = [f'"{{prop}}":{{fmt_prop(kind, a[e][i])}}' for prop, kind, a in data]
                    props += [f'"{{prop}}":{{text}}' for prop, text in constants]
                    objs.append("{{" + ",".join(props) + "}}")
                    for prop, kind, a in data:
                        if prop == "pt":
                            pt = float(a[e][i])
                            if prev_pt is not None and pt > prev_pt:
                                raise SystemExit(
                                    f"collection {{key}}: entry {{e}}: not pT-descending at index {{i}}"
                                )
                            prev_pt = pt
                parts.append(f'"{{key}}":[' + ",".join(objs) + "]")
            if met is not None and int(met[0][e]) > 0:
                parts.append(
                    '"MET":{{"pt":' + jnum(met[1][e][0]) + ',"phi":' + jnum(met[2][e][0]) + "}}"
                )
            for key, counts, a in scalars:
                if int(counts[e]) > 0:
                    parts.append(f'"{{key}}":' + jnum(a[e][0]))
            if weight is not None and int(weight[0][e]) > 0:
                parts.append('"weight":' + jnum(weight[1][e][0]))
            out.write("{{" + ",".join(parts) + "}}\n")


if __name__ == "__main__":
    main()
"#
    )
}
