//! Generator for `to_jsonl.py` — the independent uproot oracle
//! (SPEC_EVENT_PIPELINE §1.1 path (b)).
//!
//! The script reads the same ROOT file with uproot 5.x (a reader that
//! shares no code with oxyroot) and must produce **byte-identical** JSONL
//! to the native reader. It is generated from the same [`Profile`] data
//! table that drives the native path, so the *mapping* has one source of
//! truth while the *readers* stay independent. It doubles as the no-Rust
//! fallback for collaborators.
//!
//! Number text: the native side emits serde_json/ryu shortest-round-trip
//! floats. The script's `jnum` converts CPython `repr` (also shortest
//! round-trip — same digit strings) to the same notation: ryu's plain
//! decimal region is exponent −5..=15 where CPython switches to
//! scientific below −4, and CPython zero-pads negative exponents where
//! ryu does not. Positive exponents (≥ 16) already agree (`1e+16`).

use crate::profile::{CounterStyle, LeafKind, Profile};
use std::fmt::Write as _;

/// Canonical JSON text of an f64 (shared with the reader's emitter).
fn jnum(v: f64) -> String {
    serde_json::to_string(&v).expect("finite f64 serializes")
}

fn py_str(s: &str) -> String {
    format!("\"{}\"", s.replace('\\', "\\\\").replace('"', "\\\""))
}

/// Render the `to_jsonl.py` oracle script for `profile`.
#[must_use]
pub fn to_jsonl_py(profile: &Profile) -> String {
    let mut tables = String::new();

    // Naming convention (Delphes dotted/`_size`/one-element vs NanoAOD
    // underscored/`n<branch>`/flat scalars) — drives the helpers below.
    let counter_kind = match profile.naming.counter {
        CounterStyle::SizeSuffix => "size",
        CounterStyle::NPrefix => "n",
    };
    let _ = writeln!(tables, "LEAF_SEP = {}", py_str(profile.naming.leaf_sep));
    let _ = writeln!(tables, "COUNTER_KIND = {}", py_str(counter_kind));
    let _ = writeln!(
        tables,
        "FLAT_EVENT_VARS = {}",
        if profile.naming.flat_event_vars {
            "True"
        } else {
            "False"
        }
    );

    // COLLECTIONS = [(branch, key, [(leaf, prop, kind), ...], [(prop, text), ...]), ...]
    tables.push_str("COLLECTIONS = [\n");
    for c in &profile.collections {
        let leaves: Vec<String> = c
            .leaves
            .iter()
            .map(|l| {
                let kind = match l.kind {
                    LeafKind::F32 => "\"f\"".to_owned(),
                    LeafKind::I32 => "\"i\"".to_owned(),
                    LeafKind::Bool => "\"b\"".to_owned(),
                    LeafKind::TagBit(bit) => format!("(\"tag\", {bit})"),
                };
                format!("({}, {}, {kind})", py_str(&l.leaf), py_str(&l.prop))
            })
            .collect();
        let constants: Vec<String> = c
            .constants
            .iter()
            .map(|(prop, v)| format!("({}, {})", py_str(prop), py_str(&jnum(*v))))
            .collect();
        let _ = writeln!(
            tables,
            "    ({}, {}, [{}], [{}]),",
            py_str(&c.branch),
            py_str(&c.key),
            leaves.join(", "),
            constants.join(", ")
        );
    }
    tables.push_str("]\n");

    match &profile.met {
        Some(m) => {
            let _ = writeln!(
                tables,
                "MET = ({}, {}, {})",
                py_str(&m.branch),
                py_str(&m.pt_leaf),
                py_str(&m.phi_leaf)
            );
        }
        None => tables.push_str("MET = None\n"),
    }

    tables.push_str("SCALARS = [\n");
    for s in &profile.scalars {
        let _ = writeln!(
            tables,
            "    ({}, {}, {}),",
            py_str(&s.branch),
            py_str(&s.leaf),
            py_str(&s.key)
        );
    }
    tables.push_str("]\n");

    match &profile.weight {
        Some(w) => {
            let _ = writeln!(
                tables,
                "WEIGHT = ({}, {})",
                py_str(&w.branch),
                py_str(&w.leaf)
            );
        }
        None => tables.push_str("WEIGHT = None\n"),
    }

    let header = format!(
        "#!/usr/bin/env python3\n\
         # to_jsonl.py — generated by smash2 (adl-ingest) for profile {id}.\n\
         # Independent ingestion oracle: reads the {name}-layout ROOT file with\n\
         # uproot 5.x and writes the canonical JSONL event stream. Output must\n\
         # be byte-identical to `smash2 ingest <file> --profile {name} -o ...`.\n\
         #\n\
         # Usage: python3 to_jsonl.py events.root events.jsonl\n\
         # Needs: uproot 5.x (pip install 'uproot>=5,<6'); see the repo's\n\
         # .venv-uproot for the pinned environment.\n",
        id = profile.id(),
        name = profile.name,
    );

    let tree = py_str(&profile.tree);

    format!(
        r#"{header}
import os
import sys

import uproot

TREE = {tree}
{tables}

def jnum(x):
    """serde_json/ryu-compatible shortest round-trip float text."""
    x = float(x)
    if x != x or x in (float("inf"), float("-inf")):
        raise SystemExit(f"non-finite value {{x!r}} (unrepresentable in canonical JSONL)")
    s = repr(x)
    if "e" not in s:
        return s
    m, e = s.split("e")
    ei = int(e)
    if ei >= 16:
        return f"{{m}}e+{{ei}}"  # CPython and ryu agree here
    if ei == -5:
        # ryu's plain-decimal region reaches e-5; CPython went scientific.
        sign = "-" if m.startswith("-") else ""
        digits = m.lstrip("-").replace(".", "")
        return sign + "0.0000" + digits
    return f"{{m}}e-{{abs(ei)}}"  # strip CPython's zero-padded exponent


def fmt_prop(kind, v):
    if kind == "f":
        return jnum(v)
    if kind == "i":
        return str(int(v))
    if kind == "b":
        return "1" if v else "0"
    tag, bit = kind
    assert tag == "tag"
    return str((int(v) >> bit) & 1)


def main():
    if len(sys.argv) != 3:
        raise SystemExit("usage: to_jsonl.py events.root events.jsonl")
    tree = uproot.open(sys.argv[1])[TREE]
    keys = set(tree.keys())

    def leaf_branch(branch, leaf):
        return branch if leaf == "" else f"{{branch}}{{LEAF_SEP}}{{leaf}}"

    def counter_name(branch):
        return ("n" + branch) if COUNTER_KIND == "n" else f"{{branch}}_size"

    def has(branch, leaf):
        name = leaf_branch(branch, leaf)
        return name in keys or f"{{branch}}/{{name}}" in keys

    def arr(branch, leaf):
        name = leaf_branch(branch, leaf)
        if name not in keys:
            name = f"{{branch}}/{{name}}"
        return tree[name].array()

    def counter(branch):
        return tree[counter_name(branch)].array()

    n = tree.num_entries
    cols = []
    for branch, key, leaves, constants in COLLECTIONS:
        if not any(has(branch, leaf) for leaf, _, _ in leaves) and counter_name(branch) not in keys:
            continue  # collection absent from this file
        counts = counter(branch)
        data = [(prop, kind, arr(branch, leaf)) for leaf, prop, kind in leaves]
        for prop, _, a in data:
            for e in range(n):
                if len(a[e]) != counts[e]:
                    raise SystemExit(
                        f"{{branch}}.{{prop}}: entry {{e}}: {{len(a[e])}} values vs counter {{counts[e]}}"
                    )
        cols.append((key, counts, data, constants))

    # MET / scalars / weight: flat one-value-per-event scalars (NanoAOD) or
    # one-element collection branches read via a counter (Delphes).
    if FLAT_EVENT_VARS:
        met = None
        # Gate on BOTH leaves: MET needs pt and phi (mirrors load_met, which
        # drops MET if either flat scalar is absent).
        if MET is not None and has(MET[0], MET[1]) and has(MET[0], MET[2]):
            met = (arr(MET[0], MET[1]), arr(MET[0], MET[2]))
        scalars = [(key, arr(branch, leaf)) for branch, leaf, key in SCALARS if has(branch, leaf)]
        weight = (
            arr(WEIGHT[0], WEIGHT[1])
            if WEIGHT is not None and has(WEIGHT[0], WEIGHT[1])
            else None
        )
    else:
        met = None
        if MET is not None and (has(MET[0], MET[1]) or has(MET[0], MET[2])):
            met = (counter(MET[0]), arr(MET[0], MET[1]), arr(MET[0], MET[2]))
        scalars = [
            (key, counter(branch), arr(branch, leaf))
            for branch, leaf, key in SCALARS
            if has(branch, leaf)
        ]
        weight = None
        if WEIGHT is not None and has(WEIGHT[0], WEIGHT[1]):
            weight = (counter(WEIGHT[0]), arr(WEIGHT[0], WEIGHT[1]))

    # Validate-before-emit: build the whole document in memory first so a
    # non-finite value (jnum raises) or an ordering violation fails closed
    # with NO partial artifact, then write atomically via a temp file +
    # os.replace. This mirrors the native reader, which validates fully and
    # only then writes (and never truncates a pre-existing good file).
    lines = []
    for e in range(n):
        parts = []
        for key, counts, data, constants in cols:
            objs = []
            prev_pt = None
            for i in range(int(counts[e])):
                props = [f'"{{prop}}":{{fmt_prop(kind, a[e][i])}}' for prop, kind, a in data]
                props += [f'"{{prop}}":{{text}}' for prop, text in constants]
                objs.append("{{" + ",".join(props) + "}}")
                for prop, kind, a in data:
                    if prop == "pt":
                        pt = float(a[e][i])
                        if prev_pt is not None and pt > prev_pt:
                            raise SystemExit(
                                f"collection {{key}}: entry {{e}}: not pT-descending at index {{i}}"
                            )
                        prev_pt = pt
            parts.append(f'"{{key}}":[' + ",".join(objs) + "]")
        if FLAT_EVENT_VARS:
            if met is not None:
                parts.append('"MET":{{"pt":' + jnum(met[0][e]) + ',"phi":' + jnum(met[1][e]) + "}}")
            for key, a in scalars:
                parts.append(f'"{{key}}":' + jnum(a[e]))
            if weight is not None:
                parts.append('"weight":' + jnum(weight[e]))
        else:
            if met is not None and int(met[0][e]) > 0:
                parts.append(
                    '"MET":{{"pt":' + jnum(met[1][e][0]) + ',"phi":' + jnum(met[2][e][0]) + "}}"
                )
            for key, counts, a in scalars:
                if int(counts[e]) > 0:
                    parts.append(f'"{{key}}":' + jnum(a[e][0]))
            if weight is not None and int(weight[0][e]) > 0:
                parts.append('"weight":' + jnum(weight[1][e][0]))
        lines.append("{{" + ",".join(parts) + "}}")

    out_path = sys.argv[2]
    tmp_path = out_path + ".tmp"
    try:
        with open(tmp_path, "w", encoding="utf-8", newline="\n") as out:
            for line in lines:
                out.write(line + "\n")
        os.replace(tmp_path, out_path)
    except BaseException:
        try:
            os.unlink(tmp_path)
        except OSError:
            pass
        raise


if __name__ == "__main__":
    main()
"#
    )
}
