#include "adl2/ingest/ingest.hpp"

#include "jnum.hpp"

#include <sstream>

namespace adl2::ingest {
namespace {

std::string py_str(const std::string& s) {
  std::string o = "\"";
  for (char c : s) {
    if (c == '\\') o += "\\\\";
    else if (c == '"') o += "\\\"";
    else o.push_back(c);
  }
  o += '"';
  return o;
}

std::string kind_py(const LeafSpec& l) {
  switch (l.kind) {
    case LeafKind::F32: return "\"f\"";
    case LeafKind::I32: return "\"i\"";
    case LeafKind::Bool: return "\"b\"";
    case LeafKind::TagBit: return "(\"tag\", " + std::to_string(l.tag_bit) + ")";
  }
  return "\"f\"";
}

}  // namespace

std::string to_jsonl_py(const Profile& profile) {
  std::ostringstream tables;
  const char* counter_kind = profile.naming.counter == CounterStyle::NPrefix ? "n" : "size";
  tables << "LEAF_SEP = " << py_str(profile.naming.leaf_sep) << "\n";
  tables << "COUNTER_KIND = " << py_str(counter_kind) << "\n";
  tables << "FLAT_EVENT_VARS = " << (profile.naming.flat_event_vars ? "True" : "False") << "\n";
  tables << "COLLECTIONS = [\n";
  for (const auto& c : profile.collections) {
    tables << "    (" << py_str(c.branch) << ", " << py_str(c.key) << ", [";
    for (std::size_t i = 0; i < c.leaves.size(); ++i) {
      if (i) tables << ", ";
      tables << "(" << py_str(c.leaves[i].leaf) << ", " << py_str(c.leaves[i].prop) << ", "
             << kind_py(c.leaves[i]) << ")";
    }
    tables << "], [";
    for (std::size_t i = 0; i < c.constants.size(); ++i) {
      if (i) tables << ", ";
      tables << "(" << py_str(c.constants[i].first) << ", " << py_str(jnum(c.constants[i].second))
             << ")";
    }
    tables << "]),\n";
  }
  tables << "]\n";
  if (profile.met) {
    tables << "MET = (" << py_str(profile.met->branch) << ", " << py_str(profile.met->pt_leaf)
           << ", " << py_str(profile.met->phi_leaf) << ")\n";
  } else {
    tables << "MET = None\n";
  }
  tables << "SCALARS = [\n";
  for (const auto& s : profile.scalars) {
    tables << "    (" << py_str(s.branch) << ", " << py_str(s.leaf) << ", " << py_str(s.key)
           << "),\n";
  }
  tables << "]\n";
  if (profile.weight) {
    tables << "WEIGHT = (" << py_str(profile.weight->branch) << ", " << py_str(profile.weight->leaf)
           << ")\n";
  } else {
    tables << "WEIGHT = None\n";
  }

  std::string header =
      "#!/usr/bin/env python3\n"
      "# to_jsonl.py — generated by smash2_cpp (adl2_ingest) for profile " +
      profile.id() +
      ".\n"
      "# Independent ingestion oracle: reads the " +
      profile.name +
      "-layout ROOT file with\n"
      "# uproot 5.x and writes the canonical JSONL event stream. Output must\n"
      "# be byte-identical to `smash2_cpp ingest <file> --profile " +
      profile.name +
      " -o ...`.\n"
      "#\n"
      "# Usage: python3 to_jsonl.py events.root events.jsonl\n"
      "# Needs: uproot 5.x (pip install 'uproot>=5,<6'); see the repo's\n"
      "# .venv-uproot for the pinned environment.\n";

  static const char kBody[] = R"PY(
import os
import sys

import uproot

TREE = )PY";

  static const char kRest[] = R"PY(

def jnum(x):
    """serde_json/ryu-compatible shortest round-trip float text."""
    x = float(x)
    if x != x or x in (float("inf"), float("-inf")):
        raise SystemExit(f"non-finite value {x!r} (unrepresentable in canonical JSONL)")
    s = repr(x)
    if "e" not in s:
        return s
    m, e = s.split("e")
    ei = int(e)
    if ei >= 16:
        return f"{m}e+{ei}"  # CPython and ryu agree here
    if ei == -5:
        # ryu's plain-decimal region reaches e-5; CPython went scientific.
        sign = "-" if m.startswith("-") else ""
        digits = m.lstrip("-").replace(".", "")
        return sign + "0.0000" + digits
    return f"{m}e-{abs(ei)}"  # strip CPython's zero-padded exponent


def fmt_prop(kind, v):
    if kind == "f":
        return jnum(v)
    if kind == "i":
        return str(int(v))
    if kind == "b":
        return "1" if v else "0"
    tag, bit = kind
    assert tag == "tag"
    return str((int(v) >> bit) & 1)


def main():
    if len(sys.argv) != 3:
        raise SystemExit("usage: to_jsonl.py events.root events.jsonl")
    tree = uproot.open(sys.argv[1])[TREE]
    keys = set(tree.keys())

    def leaf_branch(branch, leaf):
        return branch if leaf == "" else f"{branch}{LEAF_SEP}{leaf}"

    def counter_name(branch):
        return ("n" + branch) if COUNTER_KIND == "n" else f"{branch}_size"

    def has(branch, leaf):
        name = leaf_branch(branch, leaf)
        return name in keys or f"{branch}/{name}" in keys

    def arr(branch, leaf):
        name = leaf_branch(branch, leaf)
        if name not in keys:
            name = f"{branch}/{name}"
        return tree[name].array()

    def counter(branch):
        return tree[counter_name(branch)].array()

    n = tree.num_entries
    cols = []
    for branch, key, leaves, constants in COLLECTIONS:
        if not any(has(branch, leaf) for leaf, _, _ in leaves) and counter_name(branch) not in keys:
            continue  # collection absent from this file
        counts = counter(branch)
        data = [(prop, kind, arr(branch, leaf)) for leaf, prop, kind in leaves]
        for prop, _, a in data:
            for e in range(n):
                if len(a[e]) != counts[e]:
                    raise SystemExit(
                        f"{branch}.{prop}: entry {e}: {len(a[e])} values vs counter {counts[e]}"
                    )
        cols.append((key, counts, data, constants))

    # MET / scalars / weight: flat one-value-per-event scalars (NanoAOD) or
    # one-element collection branches read via a counter (Delphes).
    if FLAT_EVENT_VARS:
        met = None
        # Gate on BOTH leaves: MET needs pt and phi (mirrors load_met, which
        # drops MET if either flat scalar is absent).
        if MET is not None and has(MET[0], MET[1]) and has(MET[0], MET[2]):
            met = (arr(MET[0], MET[1]), arr(MET[0], MET[2]))
        scalars = [(key, arr(branch, leaf)) for branch, leaf, key in SCALARS if has(branch, leaf)]
        weight = (
            arr(WEIGHT[0], WEIGHT[1])
            if WEIGHT is not None and has(WEIGHT[0], WEIGHT[1])
            else None
        )
    else:
        met = None
        if MET is not None and (has(MET[0], MET[1]) or has(MET[0], MET[2])):
            met = (counter(MET[0]), arr(MET[0], MET[1]), arr(MET[0], MET[2]))
        scalars = [
            (key, counter(branch), arr(branch, leaf))
            for branch, leaf, key in SCALARS
            if has(branch, leaf)
        ]
        weight = None
        if WEIGHT is not None and has(WEIGHT[0], WEIGHT[1]):
            weight = (counter(WEIGHT[0]), arr(WEIGHT[0], WEIGHT[1]))

    # Validate-before-emit: build the whole document in memory first so a
    # non-finite value (jnum raises) or an ordering violation fails closed
    # with NO partial artifact, then write atomically via a temp file +
    # os.replace. This mirrors the native reader, which validates fully and
    # only then writes (and never truncates a pre-existing good file).
    lines = []
    for e in range(n):
        parts = []
        for key, counts, data, constants in cols:
            objs = []
            prev_pt = None
            for i in range(int(counts[e])):
                props = [f'"{prop}":{fmt_prop(kind, a[e][i])}' for prop, kind, a in data]
                props += [f'"{prop}":{text}' for prop, text in constants]
                objs.append("{" + ",".join(props) + "}")
                for prop, kind, a in data:
                    if prop == "pt":
                        pt = float(a[e][i])
                        if prev_pt is not None and pt > prev_pt:
                            raise SystemExit(
                                f"collection {key}: entry {e}: not pT-descending at index {i}"
                            )
                        prev_pt = pt
            parts.append(f'"{key}":[' + ",".join(objs) + "]")
        if FLAT_EVENT_VARS:
            if met is not None:
                parts.append('"MET":{"pt":' + jnum(met[0][e]) + ',"phi":' + jnum(met[1][e]) + "}")
            for key, a in scalars:
                parts.append(f'"{key}":' + jnum(a[e]))
            if weight is not None:
                parts.append('"weight":' + jnum(weight[e]))
        else:
            if met is not None and int(met[0][e]) > 0:
                parts.append(
                    '"MET":{"pt":' + jnum(met[1][e][0]) + ',"phi":' + jnum(met[2][e][0]) + "}"
                )
            for key, counts, a in scalars:
                if int(counts[e]) > 0:
                    parts.append(f'"{key}":' + jnum(a[e][0]))
            if weight is not None and int(weight[0][e]) > 0:
                parts.append('"weight":' + jnum(weight[1][e][0]))
        lines.append("{" + ",".join(parts) + "}")

    out_path = sys.argv[2]
    tmp_path = out_path + ".tmp"
    try:
        with open(tmp_path, "w", encoding="utf-8", newline="\n") as out:
            for line in lines:
                out.write(line + "\n")
        os.replace(tmp_path, out_path)
    except BaseException:
        try:
            os.unlink(tmp_path)
        except OSError:
            pass
        raise


if __name__ == "__main__":
    main()
)PY";

  return header + kBody + py_str(profile.tree) + "\n" + tables.str() + kRest;
}

}  // namespace adl2::ingest
